# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leader',
            new_name='Leaderboard',
        ),
    ]
