# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20161204_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='points',
            field=models.CharField(max_length=32),
        ),
    ]
