# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20161204_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
