# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170103_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
