# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170103_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('creator', models.CharField(max_length=512)),
            ],
        ),
    ]
