# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_scenarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarios',
            name='notes',
            field=models.CharField(max_length=512),
        ),
    ]
