# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_scenarios_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenarios',
            name='name',
        ),
    ]
