# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_scenarios_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarios',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
