# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_scenarios_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarios',
            name='name',
            field=models.CharField(default=b'2017-01-11 14:00:56.715860+00:00', max_length=512),
        ),
    ]
