# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0013_auto_20170111_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarios',
            name='completedBy',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scenarios',
            name='name',
            field=models.CharField(default=b'2017-01-11 20:29:02.993924+00:00', max_length=512),
        ),
    ]
