# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0014_auto_20170111_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario_Completed_By',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='scenarios',
            name='completedBy',
        ),
        migrations.AlterField(
            model_name='scenarios',
            name='name',
            field=models.CharField(default=b'2017-01-11 21:12:56.763487+00:00', max_length=512),
        ),
        migrations.AddField(
            model_name='scenario_completed_by',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Scenarios'),
        ),
        migrations.AddField(
            model_name='scenario_completed_by',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
