# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20170111_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarios',
            name='num_lives',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='scenarios',
            name='name',
            field=models.CharField(default=b'2017-01-11 22:15:43.191278+00:00', max_length=512),
        ),
    ]
