# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20170112_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='badge_type',
            new_name='badge',
        ),
        migrations.AlterField(
            model_name='scenarios',
            name='name',
            field=models.CharField(default=b'2017-01-12 16:20:13.388053+00:00', max_length=512),
        ),
    ]
